### ISSUE TITLE
Code.gov language filter bug: C vs C#

### ISSUE THREAD

**Issue by evantayloryates** [GSA/code-gov-front-end#161] opened 2019-03-20 22:23 UTC
I found a bug on code.gov (or maybe it was intentional?). There doesn’t seem to be any differentiation between “C” and “C#” languages when filtering on a set of projects. I added a few screenshots to help illustrate the bug.
<img width="1810" alt="C" src="https://user-images.githubusercontent.com/12351038/54723186-fea9f300-4b23-11e9-87e3-9af9e745f09d.png">
<img width="1871" alt="c#" src="https://user-images.githubusercontent.com/12351038/54723188-fea9f300-4b23-11e9-9846-730ad4da1db0.png">
<img width="1870" alt="C_and_C#" src="https://user-images.githubusercontent.com/12351038/54723190-fea9f300-4b23-11e9-80b3-b40c67b6eafb.png">

**Comment by RicardoAReyes** [comment] 2019-03-21 02:27
Thank you posting the issue Taylor.

**Comment by hendersonanalytics** [comment] 2019-05-13 19:44
I think this is caused by the `code-gov-api-client` [repo code’s](https://github.com/GSA/code-gov-api-client/blob/master/src/index.js) query string parsing. Plus signs and hash tags have special meanings in urls. The hashtag (#) symbol is a [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) in URLs and plus signs in query strings are interpreted as [space characters](https://stackoverflow.com/a/2678602). When you make api calls with url-encoded versions of those characters (c%2B%2B instead of c++ and c%23 instead of c#) the correct results are returned.

**Correct C# query url**
https://api.code.gov/repos?size=10&api_key=DEMO_KEY&permissions.usageType=openSource&permissions.usageType=governmentWideReuse&language=c%23

![image](https://user-images.githubusercontent.com/5049650/57649088-ecc95700-758c-11e9-9220-b69a5d2f39ea.png)

**Correct C++ query url**
https://api.code.gov/repos?size=10&api_key=DEMO_KEY&permissions.usageType=openSource&permissions.usageType=governmentWideReuse&language=c%2B%2B

![image](https://user-images.githubusercontent.com/5049650/57649099-f357ce80-758c-11e9-87db-8f428f38e091.png)

**Comment by saracope** [comment] 2019-05-17 16:28
Fixed by @hendersonanalytics, changes are in production.

**Closed by saracope** 2019-05-17 16:28 UTC
Labels: [issue-type] bug, [issue-type] good first issue, code.gov, help wanted
