### ISSUE TITLE
Invalid Repo Web Address - Due to Null String 

### ISSUE THREAD

**Issue by AminPIC** [GSA/code-gov-front-end#198] opened 2019-05-20 13:35 UTC
**Describe the bug**
When there is either the word "null" or a null string in the repo URL field in the JSON file it still generates a URL. When you click on the "Visit Repo" link on the front-end the page does not exist. 

The best way to solve this problem would be to have a real URL check before passing the string. 

**To Reproduce**
Go to the following repo: https://code.gov/projects/va_oit_epmo_2_workload_reporting_productivity

Click Visit Repo button at the bottom

**Expected behavior**
It would open the link to the repo in Github or wherever. 

If there is no URL field, then the link wouldn't exist altogether.

**Additional context**

If a web URL/link validator is used, then perhaps the same type tool should be used in the email address field on the same page to ensure that proper email addresses are being populated on the front-end

**Comment by saracope** [comment] 2019-05-20 14:34
Closing this as a duplicate of #164.

**Closed by saracope** 2019-05-20 14:34 UTC
